apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: cloudshop
spec:
  type: {{ .Values.product.service.type }}
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: {{ .Values.product.service.port }}
      targetPort: {{ .Values.product.service.port }}
